# Generated by Django 5.2.5 on 2025-09-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('capacidad', models.IntegerField()),
                ('lugar', models.CharField(max_length=130)),
                ('artistas', models.CharField(max_length=100)),
                ('n_boletas', models.IntegerField()),
                ('costo', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('publicidad', models.CharField(max_length=50)),
                ('vestimenta', models.CharField(max_length=50)),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='flyers/')),
            ],
        ),
    ]
