# Generated by Django 5.2.5 on 2025-09-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
