# Generated by Django 5.2.5 on 2025-09-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_proyecto', '0002_alter_evento_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='flyer_patrocinadores',
            field=models.ImageField(blank=True, null=True, upload_to='patrocinadores/'),
        ),
    ]
