# Generated by Django 5.2.5 on 2025-09-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_proyecto', '0003_evento_flyer_patrocinadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='publicidad',
        ),
    ]
